name: nvidia-h100-ci

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

on:
  pull_request:
    branches: [ '*' ]
    types: [opened, synchronize, reopened, closed]
  push:
    branches:
      - main
    tags:
      - '*'

jobs:
  test-h100-pytorch-2-7:
    name: Test H100 (PyTorch 2.7)
    # Test on all main commits and PRs, but skip on closed PRs
    # to avoid running tests on merged PRs.
    if: github.event_name != 'pull_request' || github.event.action != 'closed'
    uses: ./.github/workflows/reusable-ci-tests.yml
    with:
      runner: 'nvidia-h100-pt2-7'
      gpu_type: 'nvidia'
      conda_env_name: 'pytorch_2_7'
      pytorch_version: '2.7.0'
      skip_gpu_check: true

  test-h100-pytorch-nightly:
    name: Test H100 (PyTorch Nightly)
    # Test only for open PRs pushes, skip all main branch pushes
    if: github.event_name == 'pull_request' && github.event.action != 'closed'
    uses: ./.github/workflows/reusable-ci-tests.yml
    with:
      runner: 'nvidia-h100-3'
      gpu_type: 'nvidia'
      conda_env_name: 'pytorch_nightly'
      pytorch_version: 'nightly'
      skip_gpu_check: true
